### ISSUE TITLE
React.memo

### ISSUE THREAD

**Issue by nojaf** [fable-compiler/fable-react#111]
It would be nice if we had a helper for [React.memo](https://reactjs.org/docs/react-api.html#reactmemo).
I believe @vbfox had already suggested a possible approach at FableConf. Any news on this?

**Comment by vbfox** [comment]
I'll send the PR to start discussing around it, I wanted to wait for the DevTools to have support but the PR is not merged yet ( https://github.com/facebook/react-devtools/pull/1207 ) so let's move :)
