### ISSUE TITLE
Simplified memo ?

### ISSUE THREAD

**Issue by vbfox** [fable-compiler/fable-react#118]
Little dilemma here... It's quite easy to extend `memo` support to get a much simplified usage, with this helper :

```fsharp
let simpleMemo (name: string) (render: 'props -> ReactElement) : 'props -> ReactElement =
    let memoType = memo name render
    fun props -> ofElementType memoType props []
```

Usage become as simple as :

```fsharp
// Definition
type HelloProps = { Name: string }
let hello = simpleMemo "HelloWorld" <| fun p ->
	span [] [str "Hello, "; str p.Name]

// Usage
let view model =
    hello { Name = "World" }
```

Up till there I would say :shipit: !

Until someone does that :

```fsharp
type HelloProps = { Name: string }
let view model =
    simpleMemo "HelloWorld" (fun p -> span [] [str "Hello, "; str p.Name]) { Name = "World" }
```

Or even that :

```fsharp
let view model =
    simpleMemo "HelloWorld" (fun () -> span [] [str "Hello, "; str model.Name]) ()
```

It has after all a very similar signature to all other helpers, except that this completely break all the `memo` optimizations...

Still I might find myself using it in a lot of my projects, so I don't know. What do you think ?

**Comment by MangelMaxime** [comment]
I am not sure to understand the benefit of `simpleMemo` ...

**Comment by vbfox** [comment]
One of the potential way to sidestep the problem would be to provide a more explicit name like `memoBuilder`, `createMemoBuilder`, ... something that echo the fact that the result should be saved & not used directly

**Comment by vbfox** [comment]
Ah one of the other things to consider is that while it break memo optimizations it's pretty harmless... it ends up acting like `ofFunction` so it's not much of a problem

Also the name memo (even "simple") is not something you might use accidentally so reading the function help might be something people would already do

**Comment by MangelMaxime** [comment]
Ah ok I see.

I guess if we educate correctly the person and show your minimal example as a doc comment of `memoBuilder` it should be fine.

Like that people can copy/paste the minimal example code and adapt it directly to their code.

**Comment by alfonsogarciacaro** [comment]
Hmm, `memoBuilder` with explanation in the comment would work. But I'd be in favor to keep only one API (even if I already released a version with `memo`) so users don't need to choose among many options and can just follow examples.

**Comment by MangelMaxime** [comment]
Ahah I guess that the comment explanation is ok as @alfonsogarciacaro and me answered the same thing at the same time :D

**Comment by vbfox** [comment]
Ok i'll do a PR changing the current signature

Move fast break things is one of the Facebook motto after all and they make React :)

**Comment by vbfox** [comment]
`let memo = memoBuilder` 😁

**Comment by vbfox** [comment]
memo would take the JS function name.

For anonymous functions F# doesn't support naming them.

For normal ones Fable use name mangling so the name wouldnot be good.

So in the end I preferred forcing a name to be provided.
