### ISSUE TITLE
How to make a custom HOC?

### ISSUE THREAD

**Issue by Voronar** [fable-compiler/fable-react#121]
I am trying to do the custom HOC.
There is the code:
```ocaml
type FunctionComponent<'a> = 'a -> Fable.Import.React.ReactElement
type EnhanceFunction<'a> = FunctionComponent<'a> -> 'a -> seq<Fable.Import.React.ReactElement> -> Fable.Import.React.ReactElement

type DivComponentProps = { value: string; ClassName: string;}
let enhanceDiv: EnhanceFunction<DivComponentProps> = fun comp -> fun props ->
        React.ofFunction comp { props with ClassName = props.ClassName + " red" }


type SpanComponentProps = { text: string; ClassName: string; } 
let enhanceSpan: EnhanceFunction<SpanComponentProps> = fun comp -> fun props ->
    React.ofFunction comp { props with ClassName = props.ClassName + " red" }



let SpanComponent (props: SpanComponentProps) =
    React.span [
        ClassName props.ClassName
    ] [ React.str props.text ]


let DivComponent (props: DivComponentProps) =
    React.div [
        ClassName props.ClassName
    ] [ React.str props.value ]


let EnhancedDiv = enhanceDiv DivComponent
let EnhancedSpan = enhanceSpan SpanComponent
```

How to make the general `enhance` function instead of  `enhanceDiv` and `enhanceSpan` ones?

P.S [Playground for testing current code](https://fable.io/repl/#?code=LYewJgrgNgpgBAUSsAlgZwBYDoDKLgAOsAkgHYEQAuAUNQBQBUD1cAKhvAGYCGoEacMgGMATjGAxSlAPQARGKPGTKcAiBGUYYOJxEhgiZFhYBNEBDhDupHSlLbQYuHc4g43AEbmVCVJnciQhgomkKUEE7W2mi8RDAC3CoYlJQEaABc0tIwyOjYAOYhGBAeWCgg0tQMAJS0IASShn4Y1PWNSM1YAEow3GGtDTYAYp6wWAASOQ0iaN29-W3DozATUzAzc32UWAAKemm0oJCwcD1bcAC8cCMeY5NQ07Nn-dRZcACyAPKyCAAytJQAJ4ND7gHKXZxSAHA+DvND5S7UAA+glIigkUJR8nRylosBUdhCdGqcHSoLA4KuAAZaG8AKo7WQAQVYCDxMBUEAIYES8DowHh6Th+RJ-LBUCF4pJFxYcDlwESQTgAoRAHcirK5SjhGIMSoALQAPmV4rgAGo4ABGTVwLEKXXKOBGk0UqBOq206RwABqxAQAHU4HQxPZ1lo4OrKBhTvNKLVqECQUMIGjKOVSABhfRqUjKAA8AHJuMarkWncabmNiIR1NtnnXY0glFDE-AEKQMNYhDBk6n04XixDe2F01ma7mpAPjc6y860DAAI55ysratqDSbMKbyhNvXTivLLBr2vb7e73HQkGyFAANzHOeUe3qAiuAG84DfuFAIDAyWhKCIdj5AA3HAGZQNwaBoAAcrwv5wP+gGkCBAC+1D4nAkidmiMDXjeZLtth3bDmmICkHmeH3mRj77GgJY6CmljZuWDE2AQtHljacpyvWWAgJwJHpkxhBwO+7HPhGRRgRBUGwRIELiWkWDgZBMFweacAAERwGIYDaWhl7wDgBDWFRE6UE+aQQu+mgAB6UH+AFAaBKmyXBjlISBcAoXA6EcphHZdjAxnWARgU4YJZF5iFmbZtRUiWXREKcIxQjMc6KVsRxRo2rx-GRTYaUiWJHGRtGrlqfJVyKbMFVyfAFrabp+m0OyKgxWZjp0DVZIdXF5mJdKuWxlgaAmTYADaXHcXV6k1cpMmVTANoALpwBNMZbKNAGqLRWB2SoK2tRhlH9V1PVwKd440c+Q3cZtW5gLe63TXKs3yfN73Lfda0bbxiG7c+WCft+8BHW1iDhd2YB4RCWFBbDV0PlCGGEUFYAxXDUPBeNcB9ddUJ+SoN4oDAqouuCT1jYq0YyrKT03utv02h4VCUGR61wJ8mZQCgQgANZBplcAAPosVTJmUEqOrNnGcC-QhO2aWa2lHfdrMpBzG3c+BfOC3Qwti86Es05d9qyySCsA5p+qqzaaM4TDz3viDP4QppDNaRpiFARTUAuYt9VXJpmk+Rt8v29jGO4zZMD2e71M2NpFo+8hfsB6p9Xu6HnMA3QqcIkcOSW7K4NvEyBAENQT75CIvBYMA-N4IQJyEpy3K8h+pOqsixo13XwBYGV9ZaTkzT6twleab3cD9-XZVZqQaAgLArB192M9z4PIgptQQA&html=DwCwLgtgNgfAUHUBTAhgE3gAm54ElgqbhgAOAtEgI4CuAlgG4C8A5AMID2AdmEj+QBUAnqSQtMAY268erXgA8wAenDQA3JJAoATgGcCTGmABm5ABwssOYLona6pMJO0ddujvYDmdLpl3aJJgAiElJdAC4lJRouUgBrTwA6KQglbVQJMAABAEYANmiINDSMsETSFzQaTLpuRIgfRIArXSCYYCVbe0crbBs7Byc7V3cvHz8A4NCIqJj4pJSSlEzyNA4IXIKaIqWVtYhyyuqwWq56xpa2jq7B+A6QVAwEYAAjDjQhSSgUN2CUUgoUh4KB8SG0bTgOFwaEYmDoaGCSCgDV0IHI-1IQS+P10iORdFR6IBVyUMIYdyUbw+8EQKkgsDgQA&css=BYFwtgNgNAUARgewCYE8AEBvGadoGYIB2IAtAM4CWAXgKYBcaAjAGwAOAHgNwwC+MMAOjABDCoRIBjIiFGEaAJ0zZcSCmVYRhKBngg0uynAHcKSEMAaMADFYCk3XGmA0KAc1CWb9w2gBWAVzIQCjwUSWkaYgYJSJAFB1xhCDdxCjiwMmjY+J9dfRJVeRoJYKJohAh-MEJuPkExVn8QJUdWYSRVQlcGAQAmAFYisAScAmJyanomNgNHEzMLNAGrDhG0EXlXMRJEEBAEMEsh2sEipBbcKQgEeQYz2qA).

**Comment by alfonsogarciacaro** [comment]
Hmm, the problem here is that F# doesn't have ad-hoc polymorphism. Sometimes it's possible to emulate it using inline functions and SRTP, but here you need access both to the member and the constructor so the syntax can become very cumbersome (not sure if it's even possible).

If you don't mind using interfaces, you can achieve a similar effect with flexible types:

```fsharp
type IAddClass<'T> =
    abstract AddClass: string -> 'T

type DivComponentProps =
    { value: string; ClassName: string }
    interface IAddClass<DivComponentProps> with
        member this.AddClass c = { this with ClassName = this.ClassName + " " + c }

type SpanComponentProps =
    { text: string; ClassName: string }
    interface IAddClass<SpanComponentProps> with
        member this.AddClass c = { this with ClassName = this.ClassName + " " + c }

let enhance comp (props: #IAddClass<'props>) =
    React.ofFunction comp (props.AddClass "red")

let SpanComponent (props: SpanComponentProps) =
    React.span [
        ClassName props.ClassName
    ] [ React.str props.text ]

let DivComponent (props: DivComponentProps) =
    React.div [
        ClassName props.ClassName
    ] [ React.str props.value ]

let EnhancedDiv = enhance DivComponent
let EnhancedSpan = enhance SpanComponent
```

**Comment by Voronar** [comment]
That is to say what I can't make generic implementation of this code piece:
```ocaml
member this.AddClass c = { this with ClassName = this.ClassName + " " + c }
```
and I must duplicate the implementation for all types, that implements interface `IAddClass`?

**Comment by alfonsogarciacaro** [comment]
Hmm, not that I can think of. Maybe there is a way using [something like FSharpPlus](https://github.com/fsprojects/FSharpPlus) but I'm not sure. AFAIK there's no way to make record constructors generic. If you prefer not to use interfaces, I think the common way is to pass the transform in a parameter (as with a functor):

```fsharp
type DivComponentProps =
    { value: string; ClassName: string }

type SpanComponentProps =
    { text: string; ClassName: string }

let enhance comp (addClass: 'props->string->'props) (props: 'props) =
    React.ofFunction comp (addClass props "red")

let SpanComponent (props: SpanComponentProps) =
    React.span [
        ClassName props.ClassName
    ] [ React.str props.text ]

let DivComponent (props: DivComponentProps) =
    React.div [
        ClassName props.ClassName
    ] [ React.str props.value ]

let EnhancedDiv = enhance DivComponent (fun p c ->
    { p with ClassName = p.ClassName + " " + c })

let EnhancedSpan = enhance SpanComponent (fun p c ->
    { p with ClassName = p.ClassName + " " + c })
```

**Comment by Voronar** [comment]
According to this declined suggestion by @dsyme HOC via record is impossible even in a future.
https://fslang.uservoice.com/forums/245727-f-language/suggestions/9633858-structural-extensible-records-like-elm-concrete
