### ISSUE TITLE
How to use render props with prop getters (e.g. Downshift)

### ISSUE THREAD

**Issue by cmeeren** [fable-compiler/fable-react#132]
I'm stuck trying to create bindings for [Downshift](https://github.com/paypal/downshift). Have a look at the first example in the "Usage" section of the readme.

In short: The way Downshift works, is that the child of `<Downshift>` isn't a react component, but a function that takes an object – let's call it `StateAndHelpers` – with various state and prop getters and returns a react element. That way, you can customize exactly how things are rendered, but let Downshift control the state and supply necessary props to the building blocks you want.

Now, consider for example the following simplified code from the usage example:

```jsx
<li {...getItemProps({key: item.value})}>{item.value}</li>
```

`getItemProps` is a property on the `StateAndHelpers` object. It is a function which returns an object that contains necessary props for the list item component, and you pass it other props (such as `key` above) that are merged into the final props for the list item component.

What I am struggling with, is that `getItemProps` returns an `obj`, not `seq<IHTMLProp>`. The Fable react helpers accept `seq<IHTMLProp>`, not `obj`. So it seems I can't use the `li [] []` syntax, because I have no way (that I know of) of going from `obj` to `seq<IHTMLProp>`.

Are there good solutions to using a React component like `Downshift` in Fable, or is this bound to be a painful process?

**Comment by cmeeren** [comment]
I found a way to do it, based on this function to get the properties of an object as a `(string * obj) list`:

```f#
[<Emit("
var keys = [];
for(var key in $0){ keys.push([key, $0[key]]); }
return keys;
")>]
let toKeyValueList (o: obj) : (string * obj) list = jsNative
```

With this, I am able to expose e.g. `getInputProps` with the signature `seq<IHTMLProp> -> seq<IHTMLProp>` (instead of `obj -> obj`) like this (taken out of context and somewhat modified for clarity):

```f#
let fableGetInputProps (props: seq<IHTMLProp>) =
  props
  |> keyValueList CaseRules.LowerFirst  // convert to obj
  |> downshiftGetInputProps  // downshiftGetInputProps has signature obj -> obj
  |> toKeyValueList  // function defined above, we now have (string * obj) list
  |> Seq.map (fun kv -> kv |> HTMLAttr.Custom :> IHTMLProp)  // Convert to seq<IHTMLProp>
```

There's some more boilerplate in the bindings regarding converting necessary objects/functions between the public and downshift versions, but this is hidden from users.

Closing this, but do let me know if this is a bad way to solve the problem.

**Comment by alfonsogarciacaro** [comment]
OMG, why every React component library needs to invent their own way to pass props and children? 😬As commented [here](https://github.com/fable-compiler/Fable/issues/1692#issuecomment-450742216) the Fable.React helpers use F# lists to be more idiomatic, but if you need to operate with raw prop objects, you can define your own [`domEl`](https://github.com/fable-compiler/fable-react/blob/0a0bd8821e738070857ea81219ab0620a89d3e1c/src/Fable.React/Fable.Helpers.React.fs#L1046) that doesn't apply the `keyValueList` transformation. For example:

```fsharp
let inline rawDomEl (tag: string) (props: obj) (children: ReactElement seq): ReactElement =
    createElement(tag, props, children)

// Usage
let render rawProps =
    rawDomEl "div" rawProps [p [] [str "A text"]
```
