### ISSUE TITLE
API for React Hooks

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fable-compiler/fable-react#140]
Seems React Hooks will be shipping in stable form soon and the API doesn't seem to have changed much. We will have to add bindings for them soon and as usual we've two alternatives: a) match the native API as close as possible, or b) be a bit imaginative and try to make something more F# friendly. I've been playing with the two.

### Matching native API

```fsharp
type Hooks =
    [<Import("useState", from="react")>]
    static member useState<'T> (initialState: 'T): 'T * ('T->unit) = jsNative

    [<Import("useEffect", from="react")>]
    static member useEffect<'T> (effect: unit -> (unit->unit) option, ?checkValues: obj[]): unit = jsNative

// Usage
type Props =
    { MessageFormat: string }

let MyComponent (props: Props) =
    let state, setState = Hooks.useState("")

    Hooks.useEffect(fun () ->
        printfn "New render: %s" state
        None)

    div [ Class "main-container" ]
        [ input [ Class "input"
                  Value state
                  OnChange (fun ev -> ev.target?value |> setState) ]
          span [ ]
            [ str (String.Format(props.MessageFormat, state)) ] ]

ofFunction MyComponent { MessageFormat = "Hello, {0}!" } []
|> mountById "app"
```

[REPL Example](https://fable.io/repl/#?code=PYBwpgdgBAygngZwC5gLYChSSgMQIYBGANmAHQDCwATmJuNPsWZTaQFIICSEKVod2RiVIAJMEXBUEpAEpg8AYyQCGhYWIlgps+UtIAFPiATp0AejNQA6gAtsEYEigBXBAEsIAcyhI7UGQCi+gAyUDSowABuYD5+AahuTnhISFRuBM4oCFB4EAAmLhAKwKiokE6cqCDUykhw4FAiwMAA1tkAvOhQ3VAWUADaADyV1VRIABQARK5gMEjJYJMANFAAZnyo7ZM0ikiTAJQAfAC6XT1D8YlTcrukM3ML4wAkAAyk7-sHJ2fdyMluCigZVQBC0LgQs3mKEGAHIACqHKDjDyJNx4IgPFAALig8P2OPhUAAVEj4QBaQ7OCCJfZQdpQABWCAAcv9oqYer1LEMRjUpjMAqtVmAlMs1hstjtRUdTpyLgkJpMbnoBUKRRNXu9SJ8ZT8oH8kACgWhQVRwWBBcKlLCEUiwGqlDiqYkoBSkc6kBSPbTQIbgBAVgB+BR2BQtABq6OcYAQOOABAZ-WO+MKLvpTNZhvZpjqDUMoA6eoA3lAALIxhB4TxgHDUVDJHHINJeKAAX1MJCcpbglCq-vKSJARljUHzxlpnU5nf1ULAKwhSExMXpTVa0nus6mBw5PVXbTuEMt6vGqypSNpFL1nKHHiQq2gk2ZYAA7mFIHktDiAKQISYzhZXj0zL9vsO7dHkbiRAMUDkEQeAINkkz1h4ZLFDweAeFof6ypy5xQB4ICZNBsHwYhBGZJMgG4dRUCRkQ0b-igVE0ZyADyEDkDYuTVkip7QGAUFugJpDzFQ1ZIIGkRRjEAA+iILkutI4SxCAgLk0HKSx0FNkiczNp4pC1lQ9YTEOBakOWCFVjWdbJPOs77EpUCnJgqw4FSShuP6ZY9iU1QQAOJaWZW1ZGSZdJQJMGhEMAKxFi8rYAIR-q2AynHJQLAFSSAAEJwJwBSTHgIAgJRQA&html=DwCwLgtgNgfAUHUBTAhgE3gAm54ElgqbhgAOAtEgI4CuAlgG4C8A5AMID2AdmEj+QBUAnqSQtMAY268erXgA8wAenDQA3JJAoATgGcCTGmABm5ABwssOYLona6pMJl3aJTAEQlSugFxKlNFykANYA5gB0UhBK2qgSYAACXEiKARBoMXFg4aTaHGg08XTc4RB0XOEAVrruMMBKtvaOVtg2dg5OLm6eYGS+-oEhEVGZKPHkaBwQSSnKNOmj45MQOXkFRSVlFdW19Y0d8PUgqBgIwABG+UItuGiMmHRoHiikpLtKdwyHSpdo12cqSCwOBAA&css=BYFwtgNgNAUARgewCYE8AEBvGadoGYIB2IAtAM4CWAXgKYBcaAjAGwAOAHgNwwC+MMAOjABDCoRIBjIiFGEaAJ0zZcSCmVYRhKBngg0uynAHcKSEMAaMADFYCk3XGmA0KAc1CWb9w2gBWAVzIQCjwUSWkaYgYJSJAFB1xhCDdxCjiwMmjY+J9dfRJVeRoJYKJohAh-MEJuPkExVn8QJUdWYSRVQlcGAQAmAFYisAScAmJyanomNgNHEzMLNAGrDhG0EXlXMRJEEBAEMEsh2pggA)

> I tried to create two overloads for `useEffect` but using the `effect: unit -> (unit->unit)` signature conflicts with Fable's uncurrying optimization.

### Let's be imaginative

For example to encourage creation of `memo` stateful components:

```fsharp
[<Import("*", "react")>]
[<Emit("""$0.memo(function (props) {
    const [state, useState] = $0.useState($1);
    return $2(props, state, useState);
})""")>]
let memoWithState<'P,'S> (initState: 'S) (f: 'P->'S->('S->unit)->ReactElement): ReactElementType<'P> = jsNative

type Props = { MessageFormat: string }

let MyComponent =
    memoWithState "" <| fun (props: Props) state setState ->
        div [ Class "main-container" ]
            [ input [ Class "input"
                      Value state
                      OnChange (fun ev -> ev.target?value |> setState) ]
              span [ ]
                [ str (String.Format(props.MessageFormat, state)) ] ]

ReactElementType.create MyComponent { MessageFormat = "Hello, {0}!" } []
|> mountById "app"
```

[REPL Example](https://fable.io/repl/#?code=PYBwpgdgBAygngZwC5gLYChSSgMQIYBGANmAHQDCwATmJuNPsWZTaQFIICSEKVod2RiVKdUIaklIAlMHgDGSAQ0LCAEmCLgqCabIVLcKsus1htu+ZIAKfEAnToA2gB4AoqgCWSABQAifzKWpKhowN4AZgCuEAoewNDeILYIAJRQAN7oUNlQcvHIUI7IeCgANFCRCGAwSCVgALpQALxQgQqkldW1KN4AJAAMKQDcWTk0SJFU0L0AjInJ5cVlFVU1dcPoAL4p-r4pAHz16CRIUCGowADqXgAWayjOAORWpY8w+1DeHhBe92AAXFA3mkIoDngBafZvSHeaH7aJeFKQtpIVwkEI8FKAlFotCQJAAFTg4CeVg+LQAVggAHIlDwAN1o6CQxLAUBsoAQzVG2XSUAAsmAEAg8ABzMA4aioEqA5BUb6iqCbBwnAVwShieL47k5M6ha5IO7dNn+KDOAA+UCiCSSnMBHLsaSWbKqSD+UEhPN1UAAJgzClByEQ8MKoL5pd9wXkeHhvmZfFAjt7kwHviBIqdHIHg6HfGmM74vSnizkAGp4IiRF3Gosl4sAeQg5BueAg4s+1qgYHpHo+3dItSo4qQAH56RWq1BzR9XX80km6zkECBWwGF4uclm5Z8avK26RJVRpT5bXZSILhWKJVKSotjSl54mHDj0fiieBSHIaHU1RrxBBtT5C8RXFQ9j2aMMTCIYBynSfpNgAQgTTZCiOaczmAaIkAAITgTgfTDPAQBAQsgA&html=DwCwLgtgNgfAUHUBTAhgE3gAm54ElgqbhgAOAtEgI4CuAlgG4C8A5AMID2AdmEj+QBUAnqSQtMAY268erXgA8wAenDQA3JJAoATgGcCTGmABm5ABwssOYLona6pMJl3aJTAEQlSugFxKlNFykANYA5gB0UhBK2qgSYAACXEiKARBoMXFg4aTaHGg08XTc4RB0XOEAVrruMMBKtvaOVtg2dg5OLm6eYGS+-oEhEVGZKPHkaBwQSSnKNOmj45MQOXkFRSVlFdW19Y0d8PUgqBgIwABG+UItuGiMmHRoHiikpLtKdwyHSpdo12cqSCwOBAA&css=BYFwtgNgNAUARgewCYE8AEBvGadoGYIB2IAtAM4CWAXgKYBcaAjAGwAOAHgNwwC+MMAOjABDCoRIBjIiFGEaAJ0zZcSCmVYRhKBngg0uynAHcKSEMAaMADFYCk3XGmA0KAc1CWb9w2gBWAVzIQCjwUSWkaYgYJSJAFB1xhCDdxCjiwMmjY+J9dfRJVeRoJYKJohAh-MEJuPkExVn8QJUdWYSRVQlcGAQAmAFYisAScAmJyanomNgNHEzMLNAGrDhG0EXlXMRJEEBAEMEsh2pggA)

> It should be possible to pass also the display name of the component but I need to make a small modification in the compiler for that (enabling passing literal strings to the `Emit` template).

What do you think? As always, having more opinionated helpers is a bit risky because we need extra documentation, we may not cover all the cases, etc. Also, it seems that there'll be more hooks coming and it's also possible to create custom hooks by combining them, so we may need to stick to the official API anyways. Something that concerns me in this case is how to enforce/recommend [the rules of hooks](https://reactjs.org/docs/hooks-overview.html#%EF%B8%8F-rules-of-hooks).

cc @vbfox @MangelMaxime @Zaid-Ajaj

**Comment by alfonsogarciacaro** [comment]
Hmm, this may be another case when I get carried away by abusing `Emit`. At first I thought the rules of hooks would prevent normal function composition, but this seems to work too:

```fsharp
let memoWithState<'P,'S> displayName (initState: 'S) (f: 'P->'S->('S->unit)->ReactElement) =
    memoBuilder displayName <| fun (p: 'P) ->
        let state, setState = Hooks.useState(initState)
        f p state setState

// Usage
type Props = { MessageFormat: string }

let MyComponent =
    memoWithState "MyComponent" "" <| fun (props: Props) state setState ->
        div [ Class "main-container" ]
            [ input [ Class "input"
                      Value state
                      OnChange (fun ev -> ev.target?value |> setState) ]
              span [] [ str (String.Format(props.MessageFormat, state)) ] ]

MyComponent { MessageFormat = "Hello, {0}!" }
|> mountById "app"
```

So we may provide the close-to-the-metal bindings and then recommend how to combine them and/or provide helpers for the most common helpers (like memoWithState).

**Comment by alfonsogarciacaro** [comment]
Those rules of hooks are tricky. They says hooks shouldn't be called from a nested function but this seems to work.

```fsharp
let MyComponent =
    memoWithState "MyCom" "" <| fun (props: Props) state setState ->
        // This is already happening in a nested call
        Hooks.useEffect(fun () ->
            printfn "New render: %s" state
            None)
        div [ Class "main-container" ]
            [ input [ Class "input"
                      Value state
                      OnChange (fun ev -> ev.target?value |> setState) ]
              span [] [ str (String.Format(props.MessageFormat, state)) ] ]
```

According to the [detailed explanation](https://reactjs.org/docs/hooks-rules.html), apparently the problems arise when the hooks are called in different order but that's not the case here. I guess that's why it's working fine 🤷‍♂️

**Comment by MangelMaxime** [comment]
I am always to provide an API as close as possible to the native implementation. And then if needed, provide helpers to make it easier for people to use in an F# friendly way. 

This allows people to just use what works via the friendly helpers while allowing them to explore other solution or specific needs they have by using the native API.

About the usage of the hooks, I don't have much idea because I don't yet understand they fully and I am still learning the `memo` feature 😂.

One thing for sure is that I don't like using `<|` operators. I know that dsyme explains all the time that we should avoid them. So we should provide an API that's clean without `<|`

**Comment by nojaf** [comment]
Not sure if I'm on board with the Hooks type as [Fable.Helpers thing](https://github.com/fable-compiler/fable-react/blob/master/src/Fable.React/Fable.React.Helpers.fs#L42).

I would stick closer to the original API.
```js
import { useState } from 'react';

function Example() {
  // Declare a new state variable, which we'll call "count"
  const [count, setCount] = useState(0);

  return (
    <div>
      <p>You clicked {count} times</p>
      <button onClick={() => setCount(count + 1)}>
        Click me
      </button>
    </div>
  );
}
```

Should that not be 

```fsharp
open Fable.React

let Example () =
    let [count, setCount] = useState(0);
    div [ ]
    [ p [ ]
        [ sprintf "You clicked %d times" count |> str ]
      button [ OnClick (fun _ -> setCount(count + 1))
        [ str "setCount(count + 1)}>
        Click me" ] ]
```

**Comment by alfonsogarciacaro** [comment]
@nojaf Unfortunately the syntax `let [count, setCount] = useState(0)` is not possible:

- **Module functions vs static methods:** as usual the problem is module functions don't accept optional arguments, `ParamArray`, et. So their capacity to emulate JS functions is limited. The state hook doesn't have an optional argument, but the effect hook does.
- **Array deconstruction:** because the single square brackets in F# are for lists, if you want to emulate array deconstruction in F# the correct syntax would be `let [|count; setCount|] = ...` (note you also need a semicolon instead of a comma which is a source of confusion as it has happened here). And there's also a big problem with this, you cannot type an array of specific length and with different types in F# so the signature of useState would become `'T -> obj array`, forcing users to make an unsafe cast of the return values.

Given that Fable compiles tuples as JS arrays, this is a great opportunity to use a tuple to type the return value of `useState`.

**Comment by nojaf** [comment]
Ok, in my sample I used a list but I meant a [tuple](https://github.com/nojaf/fable-react-hooks-sample/blob/master/src/Bindings.fs#L7).
I would use Option type to represent optional argument instead of optional arguments but that is personal preference.

**Comment by jarlestabell** [comment]
> Given that Fable compiles tuples as JS arrays, this is a great opportunity to use a tuple to type the return value of `useState`.

Yes, a tuple for the return value of `useState` would be great. :)

**Comment by mvsmal** [comment]
Hi guys, any decision/progress on this?

**Comment by alfonsogarciacaro** [comment]
An alpha version of Fable.React 5 with basic support for React hooks is already pushed: https://github.com/fable-compiler/fable-react/blob/dd4473088012ec6875420e4ea67f546c113bb855/src/Fable.React.Helpers.fs#L42-L49

However, this release depends on updates of several other packages and I need to make some testing and write a post explaining about the updates. Hopefully it'll happen this week. If you can't wait, as the binding is just a few lines, you can use directly in your project :)

**Comment by jannesiera** [comment]
I'm happily using react hooks with Fable.React 5. However, `useReducer` seems to be missing. What's the reason for this?

**Comment by MangelMaxime** [comment]
Probably an omission as it's looks similar to what Elmish does for us.

We would accept a PR for adding it :)

**Comment by nojaf** [comment]
I use this in my own projects:

```fsharp
type ReduceFn<'state,'msg> = ('state -> 'msg -> 'state)  
type Dispatch<'msg> ='msg -> unit  
let useReducer<'state,'msg> (reducer: ReduceFn<'state,'msg>) (initialState:'state) : ('state * Dispatch<'msg>)  = import "useReducer" "react"
```
