### ISSUE TITLE
Moving packages outside of this repo

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fable-compiler/fable-react#145]
Hi there!

First of all, thanks a lot for your contributions @forki, @toburger and @MangelMaxime! It's great to have several bindings available for React libraries. However, the approach of having a big repo with multiple packages is proving to be difficult to maintain, because I don't know the packages the bindings are targeting which makes reviewing, updating... difficult.

Because of this, and following what we're doing in other repos (fable-import, fable-powerpack) I'm planning to leave only the code for the Fable.React package here. Can you please move the other packages to your GH profile (or if you prefer, we can create another repo in fable-compiler org if you become the maintainers):

- Fable.React.TransitionGroup @toburger 
- Fable.ReactGoogleMaps @forki
- Fable.ReactLeaflet @MangelMaxime 
- Fable.Recharts @alfonsogarciacaro 

Thanks a lot for your help!

**Comment by MangelMaxime** [comment]
Sure, I will move it under my GH profile.

**Comment by toburger** [comment]
I have an existing repo where my transition group samples live: https://github.com/toburger/Fable.ReactTransitionGroup.Samples

I will rename it to `Fable.ReactTransitionGroup` or `Fable.React.TransitionGroup` (although there was a problem with this namespace, so I renamed it to the former one) and move the samples to a samples directory...
Let me know what else is needed to get it to work with the fable ecosystem.

**Comment by alfonsogarciacaro** [comment]
That should be enough, thanks @toburger! :clap:

**Comment by MangelMaxime** [comment]
For people who needs to move the project out of this repository:

[Here is the last commit with the projects in the repo](https://github.com/fable-compiler/fable-react/tree/9b0d6b67c129c1bced21764ad87b4fbd9d2beaa0)

- [ ] Fable.React.TransitionGroup	
- [X] Fable.React --> https://github.com/fable-compiler/fable-react/
- [ ] Fable.ReactGoogleMaps
- [x] Fable.ReactLeaflet --> https://github.com/MangelMaxime/Fable.ReactLeaflet
- [X] Fable.Recharts.Sample --> https://github.com/fable-compiler/fable-recharts
- [X] Fable.Recharts --> https://github.com/fable-compiler/fable-recharts

**Comment by toburger** [comment]
I've finally updated Fable.ReactTransitionGroup to the new API: https://github.com/toburger/Fable.ReactTransitionGroup 😅

**Comment by forki** [comment]
Ok I moved it to https://github.com/fable-compiler/Fable.ReactGoogleMaps
