### ISSUE TITLE
React Error when trying to add bindings

### ISSUE THREAD

**Issue by markpattison** [fable-compiler/fable-react#146]
I'm trying to add bindings for more Google Maps functionality, specifically the [MarkerLabel](https://developers.google.com/maps/documentation/javascript/examples/marker-labels) type.

My attempt is in [this commit](https://github.com/markpattison/FableElmishGoogleMaps/commit/6d6e5bb2bc542a87cd9e9def33c2babe7de17924) in a sample project.

I get the following errors at runtime (more detail in image).  What am I doing wrong?

`Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports. `

`InvalidValueError: setLabel: not a string; and no text property`

![image](https://user-images.githubusercontent.com/9657374/54133811-a3368180-440e-11e9-8ce6-c487144d3c3d.png)

**Comment by MangelMaxime** [comment]
From the documentation and the error `Label` should be a string. You are passing a `React.ReactElement` to it.

So using `MarkerProperties "my text"` should work.

Also, the library is using the npm package `react-google-maps` which doesn't have a type `MarkerLabel` but only `Marker` same for the official Google documentation. They are creating `new google.maps.Marker` not `new google.maps.MarkerLabel`.

**Comment by markpattison** [comment]
Sorry, I linked to the wrong Google Maps docs page.  [Here](https://developers.google.com/maps/documentation/javascript/reference/marker#MarkerLabel) is the documentation for the `MarkerLabel` interface.

But I see that this type isn't exposed in `react-google-maps`, so I guess we can't use it?

**Comment by MangelMaxime** [comment]
You can't use it directly. Last release of `react-google-maps` is one year old so perhaps it's outdated compared to the latest features of Google Maps.

You can always write the wrapper for `MarkerLabel` by looking at how it's done for the other classes.

I think we can close this issue because it's not related to the binding itself?

**Comment by markpattison** [comment]
Agreed.  Thanks for your help!

**Comment by markpattison** [comment]
PS - [this component](https://github.com/google-map-react/google-map-react) looks like it might be more up-to-date.  @forki ?
