### ISSUE TITLE
Where is createRef?

### ISSUE THREAD

**Issue by cmeeren** [fable-compiler/fable-react#154]
I'm reading up on React refs. I can't find any `createRef` in this repo. Are we supposed to only create refs using a callback? (Fine by me, I'd just like confirmation, as it influences the API design of ref props in Material-UI.)

**Comment by alfonsogarciacaro** [comment]
I didn't know about `createRef`, do you need for a class component? As we want to focus on function components and hooks in Fable.React 5, I'd recommend using the `useRef` hook (see the last example in [this section of the blog post](https://fable.io/blog/Announcing-Fable-React-5.html#react-hooks)). Would that fit your needs?

**Comment by cmeeren** [comment]
No idea, I was just wondering for the purposes of Material-UI API design. It has some ref props that accept either `obj` or `ReactElement -> unit`, and I guess the `obj` is then supposed to be the object returned by `createRef`. It seems similar to `ViewRef` in Fabulous, see example [here](https://fsprojects.github.io/Fabulous/views-animations.html#animations).

**Comment by alfonsogarciacaro** [comment]
I added the [`IRefHook` interface](https://github.com/fable-compiler/fable-react/blob/87f134633bf91da079f131c41e0f08fff9f4924e/src/Fable.React.Hooks.fs#L13-L14) as the return type of `useRef` and the [`RefHook` prop accepts it](https://github.com/fable-compiler/fable-react/blob/87f134633bf91da079f131c41e0f08fff9f4924e/src/Fable.React.Props.fs#L23-L24). I assume it must be the same (although the name IRefHook can be a bit misleading), can you give it a try?

**Comment by cmeeren** [comment]
I'm not currently in a position to try concrete stuff, this was just intended as theoretical questions for API design purposes of Material-UI (which I don't maintain; I'm just trying to clarify some stuff for https://github.com/mvsmal/fable-material-ui/issues/56).

Thanks so much for the prompt response and updates, though!

**Comment by alfonsogarciacaro** [comment]
I added `createRef` in 5.2.0, I hope it's ok :)
