### ISSUE TITLE
Add API for React.Context

### ISSUE THREAD

**Issue by DemiusAcademius** [fable-compiler/fable-react#160]
It would be nice if we had a helper for React.Context API: https://reactjs.org/docs/context.html and https://reactjs.org/docs/hooks-reference.html#usecontext
Thanks for powerfull soft

**Comment by alfonsogarciacaro** [comment]
Actually, I was considering to add that hook but didn't do it because I don't know well how the Context API work. I'll try to read a bit more and implement it, thanks for the links!

**Comment by alfonsogarciacaro** [comment]
Another question is how this would work with SSR, because we're trying to make all helpers in this library SSR compatible.

**Comment by alfonsogarciacaro** [comment]
On a quick look it doesn't look as a good fit for Elmish apps, because this kind of information usually goes in the model and using React's context may require several static references which may be even difficult because of file order in F#. Do you have an example on how React's context could work in a Fable React app?

**Comment by DemiusAcademius** [comment]
ReactContext types from original React (Flowtype)
https://github.com/facebook/react/blob/master/packages/shared/ReactTypes.js

(may be in   Consumer: ReactContext<T>, error)

export type ReactProvider<T> = {
  $$typeof: Symbol | number,
  type: ReactProviderType<T>,
  key: null | string,
  ref: null,
  props: {
    value: T,
    children?: ReactNodeList,
  },
};

export type ReactProviderType<T> = {
  $$typeof: Symbol | number,
  _context: ReactContext<T>,
};

export type ReactConsumer<T> = {
  $$typeof: Symbol | number,
  type: ReactContext<T>,
  key: null | string,
  ref: null,
  props: {
    children: (value: T) => ReactNodeList,
    unstable_observedBits?: number,
  },
};

export type ReactContext<T> = {
  $$typeof: Symbol | number,
  Consumer: ReactContext<T>,
  Provider: ReactProviderType<T>,

  _calculateChangedBits: ((a: T, b: T) => number) | null,

  _currentValue: T,
  _currentValue2: T,
  _threadCount: number,

  // DEV only
  _currentRenderer?: Object | null,
  _currentRenderer2?: Object | null,
};

**Comment by DemiusAcademius** [comment]
Another link to React.CreateContext:
https://github.com/facebook/react/blob/master/packages/react/src/ReactContext.js

**Comment by DemiusAcademius** [comment]
Context API in ReasonReact:

https://github.com/reasonml/reason-react/blob/master/src/React.re

module Context = {
  type t('props);

  [@bs.get]
  external provider:
    t('props) =>
    component({
      .
      "value": 'props,
      "children": element,
    }) =
    "Provider";
};

[@bs.module "react"] external createContext: 'a => Context.t('a) = "";

**Comment by DemiusAcademius** [comment]
Unfortunately I do not have enough knowledge to do it in F#

**Comment by DemiusAcademius** [comment]
But I use Context in React with Typescript for global authentication context and for pass props of component to child of child of child etc (without Redux or Mobx, but strongly typed)

**Comment by nojaf** [comment]
I'm also interested in this feature.
I've made a small sample https://github.com/nojaf/react-context-sample
Bindings are not perfect but perhaps they can serve as a starting point.

**Comment by DemiusAcademius** [comment]
Thanks! 
It turns out to be very simple. But I overloaded everything

**Comment by alfonsogarciacaro** [comment]
Thanks @nojaf! That's a very good example of how React context should work in F#, I'll follow that to add the bindings to Fable.React :+1:

**Comment by alfonsogarciacaro** [comment]
I've added the Context API in 5.2.1 and tried to make it compatible with SSR. You can see a usage example here: https://github.com/fable-compiler/fable-react/commit/3dfbd761f1b01cba0934a6f2aef3ca918a14f6bc#diff-fbdb47a7fd0afc448eba000af59b0221
