### ISSUE TITLE
How should I use the Context api?

### ISSUE THREAD

**Issue by 0x53A** [fable-compiler/fable-react#164]
I am currently working on a localization api for fable react.

What I want is to be able to set the language somewhere at the top, and then have the child nodes reflect this language. For that, the Context api seems to be a perfect fit.

So I want to do the equivalent to

```jsx
const LocalizationContext = React.createContext( { lang: "en" } );

// ...

// app
  render() {
    return (
      <Page>
        <LocalizationContext.Provider value={{ lang: "it" }}>

			/* imagine a few layers of sub-components and nesting */

			<LocalizationContext.Consumer>
				{value => /* render localized text based on value.lang */}
			</LocalizationContext.Consumer>

        </LocalizationContext.Provider>
      </Page>
    );
  }
  
```

Now, what initially confused me is that in Fable.React, the interface ``IContext`` is empty:

_(I would have expected two members, Provider and Consumer)_

https://github.com/fable-compiler/fable-react/blob/3dfbd761f1b01cba0934a6f2aef3ca918a14f6bc/src/Fable.React.fs#L18-L19

Then a bit later I found ``contextProvider``:

https://github.com/fable-compiler/fable-react/blob/3dfbd761f1b01cba0934a6f2aef3ca918a14f6bc/src/Fable.React.Helpers.fs#L345-L353

So that takes care of the Provider part.

--------

But I couldn't find anything like ``contextConsumer``.

How should I consume the context? Did I miss anything?

I'm not 100% sure how to translate

```jsx
			<LocalizationContext.Consumer>
				{value => /* render localized text based on value.lang */}
			</LocalizationContext.Consumer>
```

to Fable React, afaik the function should be passed as a prop named "children"? I think the following should work:

```fs
     let inline contextConsumer (ctx: IContext<'T>) (children: 'T -> ReactElement seq): ReactElement = 
#if FABLE_COMPILER 
         ReactBindings.React.createElement(ctx?Consumer, createObj ["children " ==> children ], null) 
#else 
         children((ctx :?> ISSRContext<_>).DefaultValue)
#endif 
```

If I manage to get anything working I'll send a PR ...

**Comment by alfonsogarciacaro** [comment]
Yeah, the API here differs from React. I should have written about this. IIRC, I did it this way to make it more easily compatible with SSR. About consuming, I think I was just hoping everybody would just use [the `useContext` hook](https://github.com/fable-compiler/fable-react/blob/e5461df6c9891cea9e323d56cae0e65de3c434ea/Samples/TodoMVC/src/TodoMVC.fs#L94). But I guess it's better to add `contextConsumer` for the sake of completeness :)
