### ISSUE TITLE
Make OnInput nicer

### ISSUE THREAD

**Issue by forki** [fable-compiler/fable-react#19]
https://github.com/fable-compiler/fable-elmish/blob/master/samples/react/todomvc/todomvc.fsx#L201

^^ is that the best way to do it?

**Comment by alfonsogarciacaro** [comment]
Yeah, that's a problem because there're many types of events so you need to cast `ev` to get proper typing. Not sure yet what's the best way to solve this.

**Comment by MangelMaxime** [comment]
Is there something to work here ? Or should we close ?

**Comment by MangelMaxime** [comment]
Not much we can do here.

And we provided a `.Value` member to make it a bit nicer.

**Comment by MangelMaxime** [comment]
@alfonsogarciacaro The latest version of `Fable.React` removed the `Value` sugar syntax should we re-add it with method extension as it was done?

**Comment by alfonsogarciacaro** [comment]
@MangelMaxime It should be there, you don't see it? You probably need to `open Fable.React` to activate the extension: https://github.com/fable-compiler/fable-react/blob/ea0962c2d693998cc4816a78cff8d384bca52e49/src/Fable.React.Helpers.fs#L58-L62

**Comment by MangelMaxime** [comment]
I saw it after ^^ 

Sorry :)
