### ISSUE TITLE
Need a consistent way to enter &nbsp; and other html

### ISSUE THREAD

**Issue by reinux** [fable-compiler/fable-react#192]
Currently, the workaround seems to be to do something like this:

```
let rawHtml html =
  GenericOptions.Empty.AddProp(
    DangerouslySetInnerHTML { __html = html })
    .ToReactElement span
```

`GenericOptions` depends on Fulma, and I'm not too sure how else to do this without it.

I think the only reason this is an issue is because I want to inject whitespace between two `a` elements, and `str` seems to trim them away.

**Comment by Zaid-Ajaj** [comment]
Hello @reinux, don't you simply need the `DangerouslySetInnerHTML` property on any element? i.e.
```fs
div [ DangerouslySetInnerHTML  { __html = html } ] 
    [  ] 
```

**Comment by reinux** [comment]
Derp. Thanks for that!

**Comment by MangelMaxime** [comment]
Indeed `DangerouslySetInnerHTML` that you used in your first snippet is coming from Fable.React

This is actually the expected behaviour.
