### ISSUE TITLE
React keyboard events are not working with Fable 1.x bindings

### ISSUE THREAD

**Issue by et1975** [fable-compiler/fable-react#20]
Converted [TODO](https://github.com/fable-compiler/fable-elmish/tree/next/samples/react/todomvc) sample, keyboard events are not firing, mouse seems ok.

**Comment by forki** [comment]
We should add some canopy tests to all important infrastructure projects...

**Comment by alfonsogarciacaro** [comment]
I've checked the sample and the problem was not in the bindings but unfortunately it's a regression caused by the lambda flattening in Fable 1.0, I need to fix it. Left some comments in [this commit](https://github.com/fable-compiler/fable-elmish/commit/56648e887fe08143a2d21784eb5639d11bfe7555).
