### ISSUE TITLE
Docs on 3rd-party react integration out of date

### ISSUE THREAD

**Issue by davedawkins** [fable-compiler/fable-react#202]
Re: https://github.com/fable-compiler/fable-react/blob/master/docs/using-third-party-react-components.md

This was a great page to find, and I think it will help me with what I'm trying to do.

However I think it's out-of-date, particularly since it references `[<Pojo>]`; I can't find that attribute in any namespace, and the link it references is dead. I suspect that this is a minor obstacle to creating integrations.

I'm still in the process of getting up the learning curve, so don't have any suggestions on how to bring this document up-to-date. If that changes I'll revisit and do what I can. Otherwise, if anybody is able to check it over that would be appreciated.

**Comment by alfonsogarciacaro** [comment]
Ah, you're right, sorry for that. I think this came from when React was giving warnings if you passed a class as props. But if I'm not mistaken this is not the case anymore and at one point we removed the `Pojo` attribute. I believe you should be able to pass just a record as props.

**Comment by alfonsogarciacaro** [comment]
Fixed by 57a8f5a2ec4591a32172812001cf909313f4399f
