### ISSUE TITLE
`HTMLAttr.Class` alternative that works with a list of strings

### ISSUE THREAD

**Issue by JaggerJo** [fable-compiler/fable-react#206]
Using `HTMLAttr.Class` in combination with a CSS type provider or CSS class literals lets to messy code. Would be cool to have an alternative case that takes a list of strings. 

Example:
```fsharp
Class (sprintf "%s %s %s" AdminCss.button AdminCss.buttonPrimary AdminCss.buttonLarge)
```

Instead I'd like to do something like this:
```fsharp
Classes [ AdminCss.button; AdminCss.buttonPrimary; AdminCss.buttonLarge ]
```

Would be a nice addition IMHO. 

I use a helper function for now..

**Comment by MangelMaxime** [comment]
Hello,

there already are some helpers to work with classes:

https://github.com/fable-compiler/fable-react/blob/81ca109cfd296357ea1359391e8de7dc90b4f771/src/Fable.React.Helpers.fs#L386-L395
