### ISSUE TITLE
Fix void elements in the DSL

### ISSUE THREAD

**Issue by MangelMaxime** [fable-compiler/fable-react#21]
According to [MDN](https://developer.mozilla.org/en-US/docs/Glossary/Empty_element) some HTML elements can be void.

When the React binding has been created thus elements were defined as any other (with property and children).

I propose we take the opportunity offered by the Fable 1.0 release to introduce a breaking change into the binding for thus elements.

I understand that under now we didn't make thus changes but that means we will always have this errors in the bindings. 

The breaking change isn't so hard to fix thanks to F# compiler. People having application in production would "only" need to remove the empty `[]` they used for thus elements.

**Comment by forki** [comment]
If the breaking change can be done as compile error then I'm all in.

Am 07.04.2017 12:41 vorm. schrieb "Maxime Mangel" <notifications@github.com

**Comment by MangelMaxime** [comment]
As we are changing the functions signatures the compiler should complain about them.

**Comment by alfonsogarciacaro** [comment]
If @forki and @et1975 are ok with this I'm all for it :)

**Comment by alfonsogarciacaro** [comment]
Could you please send a PR for this @MangelMaxime?

**Comment by MangelMaxime** [comment]
Yes sure :)
Will do it today.
