### ISSUE TITLE
module.hot.addStatusHandler is not a function

### ISSUE THREAD

**Issue by albertwoo** [fable-compiler/fable-react#210]
When use fable 3 I got below error:

Uncaught TypeError: module.hot.addStatusHandler is not a function
    at Fable.React.FunctionComponent.fs.js:23

**Comment by alfonsogarciacaro** [comment]
Thanks for reporting @albertwoo! I surrounded the code with a `try ... catch`. Can you please try with latest release (7.1.0)?

**Comment by albertwoo** [comment]
Got new error:
Error	FS0193	The module/namespace 'Fable.React' from compilation unit 'Fable.React' did not contain the namespace, module or type 'ReactElement'

**Comment by alfonsogarciacaro** [comment]
Strange, I'm trying Fable.React 7.1.0 in a production project and is working fine. Can you try with latest Fable 3 (rc-010) and also removing the `obj` folder just in case?

**Comment by albertwoo** [comment]
@alfonsogarciacaro the fable compiler works fine, but if I use VS 2019 to build it then I got the error.
You can use https://github.com/albertwoo/FablePlayground/tree/210 branch 210 to reproduce.

**Comment by Titaye** [comment]
Same here, `dotnet fable` compiles fine but `dotnet build` is not working (and intellisense in ionide is also complaining)

**Comment by alfonsogarciacaro** [comment]
Damn, so moving types to a separate assembly cause errors. Seems if we want to do this we need to publish a new major version and update all libraries depending on Fable.React... For now I just republished Fable.React with the interfaces back, can you please try?

**Comment by Titaye** [comment]
Everything is ok for me with version 7.2.0. `dotnet build` is working

**Comment by albertwoo** [comment]
It works for me too. 👍
