### ISSUE TITLE
Can't reference React in Fable

### ISSUE THREAD

**Issue by Montana** [fable-compiler/fable-react#214]
I am trying to write a React component in F# with Fable, and I'm having trouble referencing the necessary libraries. The compile errors I'm getting are as follows:

`The namespace 'React' is not defined. ('open' statements). The type PureStatelessComponent is not defined.`

Here is my code currently, seen a similar thread, but the solution offered in that did not work:

```f#
module ContactInfoComponent

open Fable.Core
open Fable.Core.JsInterop
open Fable.Import
open Fable.Import.Browser
open Fable.React
open Fable.React.Helpers


type ContactInfoProps = {
    Name : string
}

type ContactInfoComponent(initialProps) = 
    inherit PureStatelessComponent<ContactInfoProps>(initialProps)
    override this.render() = 

        div [] [ 
            str "Name: "
            input [Type "text" Id "txtName"]
        ]
```
I appreciate any help, thank you.

-Montana Mendy

**Comment by alfonsogarciacaro** [comment]
Not sure if that's the problem, but please make sure you're using the latest library version. Looking at the open statements it seems you're using Fable.Import.Browser which is deprecated, please use Fable.Browser.Dom instead (latest Fable.React already includes it as a dependency).

```fsharp
// Access DOM global values like window, document, etc
open Browser

// Access DOM types likes KeyboardEvent, etc
open Browser.Types
```

If this doesn't help can you please tell us:

- What's the similar thread you found?
- Where do you get the error (ide, Fable compilation logs, etc)
- What version of Fable are you using and how you run it?
- If possible, please share your .fsproj file and if you're using Paket, also paket.dependencies

**Comment by Montana** [comment]
Tried

```f#
Fable.Browser.Dom
```
Worked! Seems like I've ran into the deprecated issue before - gotta keep on it. Thank you @alfonsogarciacaro!
