### ISSUE TITLE
Q: Use ReactElement import member for Storybook

### ISSUE THREAD

**Issue by rastreus** [fable-compiler/fable-react#230]
I am trying to follow Storybook's [Default export example](https://storybook.js.org/docs/react/writing-stories/introduction#default-export).

I have a `Count.stories.fs` file:
```fsharp
module CountStories

open Fable.Core.JsInterop
open Count

let defaultExport =
    createObj [
        "title" ==> "Count"
        "component" ==> Count.CountComponent
    ]

exportDefault defaultExport
```
which Fable compiles to the following `Count.stories.fs.js` file:
```javascript
import { createElement } from "react";
import { Count_CountComponent_39D2159E } from "./Count.fs.js";

export const defaultExport = {
    title: "Count",
    component: () => createElement(Count_CountComponent_39D2159E, {}),
};

export default defaultExport;
```

What all do I need to change to get the following output for the `Count.stories.fs.js` file?
```javascript
import { Count_CountComponent_39D2159E } from "./Count.fs.js";

export const defaultExport = {
    title: "Count",
    component: Count_CountComponent_39D2159E,
};

export default defaultExport;
```

---

Is there a way for the compiled ReactElement to be `export const` rather than `export function`?
```javascript
export const Count_CountComponent_39D2159E = (count_CountComponent_39D2159EInputProps) => {
    // ... implementation
}
```

```javascript
export function Count_CountComponent_39D2159E(count_CountComponent_39D2159EInputProps) {
    // ... implementation
}
```

Any help or advice is appreciated. Thank you.

**Comment by MangelMaxime** [comment]
Hello @rastreus,

> What all do I need to change to get the following output for the `Count.stories.fs.js` file?
> 
> ```js
> import { Count_CountComponent_39D2159E } from "./Count.fs.js";
> 
> export const defaultExport = {
>     title: "Count",
>     component: Count_CountComponent_39D2159E,
> };
> 
> export default defaultExport;
> ```

Would it work if you had ?

```fs
export const defaultExport = {
    title: "Count",
    component: (props) => createElement(Count, props),
};

export default defaultExport;
```

I am asking because `(props) => createElement(Count, props)` is just a functional ReactComponent (which is unnamed (I invented this term))

----

> Is there a way for the compiled ReactElement to be `export const` rather than `export function`?

Hum, for this one this is actually related to how Fable generates JavaScript.

In theory, function definition inside of a module are unique. I believe you cannot declare twice `let test () = ()` so perhaps it possible generates the export as `const` but need to make sure that this is always true.

Otherwise, JavaScript will complained about:

> Cannot redeclare block-scoped variable 'test'

**Comment by rastreus** [comment]
@MangelMaxime Thanks for replying. I tried `Count.stories.fs` again as below. It is working. I must have had something else messed up earlier. Sorry to have taken time out of your day.

```fsharp
module CountStories

open Fable.Core.JsInterop
open Count

let defaultExport =
    createObj [
        "title" ==> "Count"
        "component" ==> Count.CountComponent
    ]

exportDefault defaultExport

let Five () =
    Count.CountComponent ({| Count = 5 |})

```

**Comment by MangelMaxime** [comment]
@rastreus No problem, glad that you made it works :)
