### ISSUE TITLE
Missing 'open' from Fable.React.Props? 

### ISSUE THREAD

**Issue by ciphertools** [fable-compiler/fable-react#231]
When updating to Fable.React 9.0.0, I couldn't get it working until I added `open Fable.Core.JsInterop` to Fable.React.Props.fs.

**Comment by alfonsogarciacaro** [comment]
Yes, sorry. I pushed a new version with the fix. Please note that the new version can still break your code if using other dependencies that haven't been updated, see #232.

**Comment by ciphertools** [comment]
Thanks for the fix.  New version now installed and my code is still working ...!
