### ISSUE TITLE
Add Pointer Events

### ISSUE THREAD

**Issue by cr3wdayt5p** [fable-compiler/fable-react#237]
**Feature request:** Add pointer events to `Fable.React.Props.DOMAttr`.

Pointer Events were added to React DOM in v16.4 back in 2018: https://reactjs.org/blog/2018/05/23/react-v-16-4.html

There is now full browser support (even back to IE11 from 2013): https://caniuse.com/?search=PointerEvent%20API

They already work fine with `DOMAttr.Custom`, e.g. `DOMAttr.Custom ("onPointerDown", handler)`.

The `PointerEvent` type is available in `Browser.Types`.

**Comment by alfonsogarciacaro** [comment]
I think that'd be fine. Would it be possible for you to send a PR? Many Fable projects have moved to Feliz so there are not many maintainers for this repo now.

**Comment by alfonsogarciacaro** [comment]
Yes, this is quite a pain with Nuget. AFAIK there's no built in solution to test local packages, so you need to create the package locally and add the local sources in the Nuget.config (and make sure the package is not cached every time you change it).

To make this easier for Fable I added a `--replace` option that can replace a package with a local project. Example:

```
dotnet fable watch src --replace Fable.React:path/to/you/local/Fable.React.fsproj
```

The only problem is this is a Fable-only mechanism. So it will work for Fable compilation but your IDE will still complain the new Props don't exist.
