### ISSUE TITLE
Using from + pojo

### ISSUE THREAD

**Issue by jgrund** [fable-compiler/fable-react#28]
Is there an example with using 

https://github.com/fable-compiler/fable-react/blob/next/fable-react/Fable.Helpers.React.fs#L588

to create an Element? I'm trying to upgrade the react native demo project to 1.0, and seem to be hitting issues here when transpiling.

**Comment by alfonsogarciacaro** [comment]
Hi @jgrund! Actually the fable-electron Material UI is probably the best example at the moment. There dynamic objects are used, which are compatible with Pojo: https://github.com/fable-compiler/fable-electron/blob/master/samples/material-ui/src/Renderer/Renderer.fs#L51-L54

> It's important to declare the imported object as a `React.ComponentClass`: https://github.com/fable-compiler/fable-electron/blob/737baef8a47abe4f82f8ce25691fb53b6484364e/samples/material-ui/src/Renderer/Renderer.fs#L10-L20
