### ISSUE TITLE
Implementation of the React Toolbox

### ISSUE THREAD

**Issue by tforkmann** [fable-compiler/fable-react#29]
For faster and nicer development it would be nice to be able to use the React Toolbox (http://react-toolbox.com/#/).

Is there a way to implement that toolbox?

Best,

Tim

**Comment by alfonsogarciacaro** [comment]
It's already possible to use imported React components using `from` even dynamically ([example with Material-UI](https://github.com/fable-compiler/fable-electron/blob/742b21bf707bb0f0b2c421f9911cc9a704756247/samples/material-ui/src/Renderer/Renderer.fs#L51-L54)). I think there was an example out there of using Fable with React Toolbox, but I don't remember where. I personally tried to use React Toolbox but had some problems with the Sass modules (also in JS) so I haven't investigated further.

**Comment by tforkmann** [comment]
Thanks you for the tip!
Found a starter pack and the helper function in:
https://github.com/Prolucid/fable-react-toolbox
https://github.com/Prolucid/fable-react-toolbox-starter

Will close that issue now!
