### ISSUE TITLE
fable 1.1.* build

### ISSUE THREAD

**Issue by et1975** [fable-compiler/fable-react#31]
Apparently I can't release Fable.Elmish.React without React bindings package that uses Fable.Browser nuget.

**Comment by alfonsogarciacaro** [comment]
Sorry, I just published Fable.React 1.1.0 (with Fable.Import.Browser dependency). Please give it a try and tell me if you still have problems. Please let me know when the new Elmish packages have been published so we can update other repos to Fable 1.1.x like the fable-suave-scaffold :+1:

Cheers!

**Comment by et1975** [comment]
Thanks, released all the elmish packages targeting Fable 1.1!

**Comment by alfonsogarciacaro** [comment]
Great, thanks for the quick release @et1975! The new packages work with fable-suave-scaffold (see https://github.com/fable-compiler/fable-suave-scaffold/pull/123). Unfortunately I also noticed I was forgetting to add a reference to `System.Console` when compiling with FCS so some WriteLine statements were failing in Elmish.Debugger when compiling with Fable. I released dotnet-fable 1.1.3 and it's working now, but in future releases you may want to depend on Fable.Core 1.1.3 minimum to make other users won't have the same problem.
