### ISSUE TITLE
Release cycle

### ISSUE THREAD

**Issue by nojaf** [fable-compiler/fable-react#37]
Any idea when would the next publish to nuget would be?
The latest commits contain some fixes I'm interested in.
What is the release policy? Is it more ad-hoc or on a monthly base?

**Comment by alfonsogarciacaro** [comment]
Sorry, I was in vacation so I couldn't check the issues very often. There's no _release policy_ at the moment, we usually just publish a new version whenever there's a new addition. However, the latest commits contain a few breaking changes so I was considering publishing a new release in the next Fable cycle with Fable being a netcore2 app and most of the libraries targeting netstandard2 (so there're no more System.XXX dependencies and we can make the `packages` folder slimmer). Hopefully this will happen this week.

If you want to use the latest changes, another possibility is to just clone this repo (or use Paket git dependencies) and add a `ProjectReference` to where `Fable.Project.fsproj` is. This won't make any difference with the generated JS code.

**Comment by nojaf** [comment]
Thanks, when adding a paket git dependency I got it working.
Interesting stuff with the netstandard 2.0, looking forward :wink:
