### ISSUE TITLE
Why is Fable.ReactLeaflet library included in this repo ?

### ISSUE THREAD

**Issue by irium** [fable-compiler/fable-react#40]
Is `ReactLeaflet` really needs to be included in *general purpose* `fable-react` lib?

I don't need it at all and don't want to download it every time I install/upgrade *the very basic* and only a *common* `fable-react`.
I guess it should be distributed by *separate, it's own repo*.

Otherwise we should include here _every_ React-integration library...

**Comment by forki** [comment]
Ok serious question: why does it matter?

**Comment by irium** [comment]
It matters because there should be orderliness and discipline in *every* thing, that relates to _organizing_ code. After all - all programming is fight with complexity. There should be clean and simple rules how to organize code at every level. (And I simply don't understand _why_ they put it here).
If we'll start to break them - it will quickly lead to chaos at least in this area: Fable-React integrations.
Otherwise I'd expect some README that explains something like "from now on we decided, that *all* Fable-React import libs should be placed here". This is also an option.

There is already a great repo for all Fable-JS integrations: [fable-import](https://github.com/fable-compiler/fable-import)

**Comment by forki** [comment]
Sorry that's not really the technical explanation that I was looking for.
Because we are actually discussing pros and cons of split versus one repo.

Am 30.10.2017 09:35 schrieb "irium" <notifications@github.com>:

**Comment by alfonsogarciacaro** [comment]
@MangelMaxime and I discussed the pros and cons before putting the extension here and at the end we agreed to include the extension in this repo but distribute it as a different package (so Fable.React users don't need to download code they won't use).

One of the reasons not to add ReactLeaflet in fable-import was that repo only contains [pure bindings](https://github.com/fable-compiler/fable-import#fable-import) which only have metadata and thus can be distributed just in .dll form. But ReactLeaflet contains actual code so it needs to include also sources in the distribution.

In any case, I agree it's a great idea to update the README. Would you mind to send a PR for that?

**Comment by MangelMaxime** [comment]
If you take a look at the dependencies listed [here](https://www.nuget.org/packages/Fable.React) you will see no one about `Fable.ReactLeaflet` so you are not downloading every time you you `Fable.React`.

And adding `Fable.ReactLeaflet` to this repo is in fact to organize the code. It's easier to maintain for us as a maintainer instead of having one repo per react package for example.

I agree with you and @alfonsogarciacaro about adding this kind of information into the README.md to help people understand the choice.

**Comment by irium** [comment]
@alfonsogarciacaro Ok, got it! Thanks for reply! The thing that `React.Leaflet` is in the separate package completely answered all of my misunderstanding.

**Comment by irium** [comment]
@alfonsogarciacaro 

> Would you mind to send a PR for that?

I've done what I can :)
