### ISSUE TITLE
SVGAttr attribute missing Height 

### ISSUE THREAD

**Issue by daz10000** [fable-compiler/fable-react#43]
Apologies but I filed the pull request before the issue.  I was exploring SVG with Fable on a flight on weekend and realized there was no obvious way to specify Height attribute for a rectangle (or the SVG tag itself).  Width is in there.  I added a local Height and everything works fine, so I sent in a PR but apologies if there was something obvious in there I missed.   Was an absolute dream getting an SVG app working in react.  thanks for a nice library!

**Comment by daz10000** [comment]
ps.  see PR #42

**Comment by MangelMaxime** [comment]
Hello @daz10000 nothing was wrong with your PR :) I just read it on my mobile and forget about it ^^.

Changes are included in Fable.React.1.2.2.
