### ISSUE TITLE
F# section in React docs

### ISSUE THREAD

**Issue by et1975** [fable-compiler/fable-react#47]
Apparently the docs are editable, maybe worth adding F# section here:
https://github.com/reactjs/reactjs.org/blob/master/content/docs/static-type-checking.md

**Comment by alfonsogarciacaro** [comment]
Good idea! I'll open an issue to ask them if it's ok to mention F# there :+1:

**Comment by et1975** [comment]
I think it needs another edit :/

**Comment by MangelMaxime** [comment]
I send one to fix the link display... Should I cancel it ?

**Comment by alfonsogarciacaro** [comment]
Sorry, what kind of edit you mean?

**Comment by et1975** [comment]
I mentbthe link, @MangelMaxime has fixed it.
