### ISSUE TITLE
Using a function as a component or element's child

### ISSUE THREAD

**Issue by nozzlegear** [fable-compiler/fable-react#48]
Hello, I'm playing around with some Mobx bindings for Fable but I'm running into one major blocker. I've got an imported component that needs to accept a function as its child. The function will be called later by the parent component and should return a list of React elements like the result of any plain render function. 

In JSX it would look like this:

```jsx
<Observer>
  {() => <div>Hello World!</div>}
</Observer>
```

I've tried using a combination of Fable React's `fn` and `from` to do this:

```fs
let imported: React.ComponentClass<_> = import "Observer" "mobx-react"
let fn = R.fn<obj> (fun _ -> R.div [] [R.str "Hello world"]) [] [R.str "Hello world 2"]
R.from<obj> imported [] [fn]
```

But while this compiles just fine, React just gives me errors saying "React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined." I assume that `fn` is actually meant for things like stateless components and I'm using it incorrectly here.

Is it possible to pass a function as the child of an imported component, or even just a react element? Any help would be appreciated, thanks for reading!

**Edit**: The React error I wrote above was incorrect and not the one I'm running into. I'm actually getting the following when trying to use a function as the component's child: "Failed prop type: Invalid prop `null` of type `object` supplied to `Observer`, expected `function`."

**Comment by alfonsogarciacaro** [comment]
Yes, `fn` is to create stateless components, so something like:

```fsharp
let Hello (o:obj) = R.div [] [R.str "Hello world"]
R.fn Hello null []
```
In JSX would be more or less:

```jsx
const Hello = () => <div>Hello World</div>;
<Hello />
```

What you want is to cast directly the function into a React without any instantiation. I had never seen this but I guess an `unbox` cast (which is erased in runtime by Fable) should work, as it's done [for other elements that React accepts](https://github.com/fable-compiler/fable-react/blob/78625ccc065c890946bbbce10804a84d67172343/src/Fable.React/Fable.Helpers.React.fs#L755) as elements (like string).

You can create a simple helper for that, please give it a try and tell me how it works :smile:

```fsharp
let Observer: React.ComponentClass<obj> = importMember "mobx-react"

let inline ofFunction2 (f: unit -> ReactElement): ReactElement = unbox f

R.from Observer null [
   ofFunction2 (fun () -> R.div [] [R.str "Hello world"])
]
```

> I'm using `ofFunction2` because I'm planning to use `ofFunction` as alias of `fn` in the next API, but of course you can use whatever you want 😸

**Comment by nozzlegear** [comment]
Awesome, that's working! Thank you for the guidance!
