### ISSUE TITLE
Add DangerousInnerHtml Pojo

### ISSUE THREAD

**Issue by MangelMaxime** [fable-compiler/fable-react#52]
In my application often need to define this type:

```fs
[<Pojo>]
type DangerousInnerHtml =
    { __html : string }
```

This is useful, when you are rendering markdown for example.

`let htmlFromMarkdown str = div [ DangerouslySetInnerHTML { __html = Marked.Globals.marked.parse (str) } ] []`

I guess we could add under `Fable.Helpers.React.Props` what do you think ?

**Comment by alfonsogarciacaro** [comment]
We're going to deprecate the `Pojo` attribute so maybe it's better to wait a bit. Another solution could be to have something like this:

```fsharp
    [<Emit("['dangerouslySetInnerHTML', { __html: $0 } ]")>
    let inline DangerouslySetInnerHTML (__html: string): HTMLAttr = jsNative
```

This would be more convenient to developers though slightly different from React spec. But the signature should help and we can also add a comment. `DangerouslySetInnerHTML` is verbose enough to be sure nobody will use this API by mistake :)

**Comment by MangelMaxime** [comment]
Using Emit seems fine to me, I will test it in my project before sending a PR

**Comment by dbrattli** [comment]
Using Emit does not work for SSR.

**Comment by MangelMaxime** [comment]
I think we implemented it without emit finally:

[Source](https://github.com/fable-compiler/fable-react/blob/87f134633bf91da079f131c41e0f08fff9f4924e/src/Fable.React.Props.fs#L27-L32)
```fs
type DangerousHtml = {
    __html: string
}

type DOMAttr =
    | DangerouslySetInnerHTML of DangerousHtml
```

So we can probably close this issue.

**Comment by dbrattli** [comment]
Thanks, that worked!
