### ISSUE TITLE
Translate HTML to Fable.React

### ISSUE THREAD

**Issue by kfrie** [fable-compiler/fable-react#53]
Hello,

I had the idea earlier, that interfacing with existing HTML could be a lot easier if there was a tool, that simply translates HTML snippets to Fable.React F# code. 

Ideally this would be shipped as VS Code plugin, so that you can select some HTML and replace it with Fable.React code.

What do you think of the idea? Or does something like that already exist?

**Comment by MangelMaxime** [comment]
In the past someone made a quick prototype of this [available here](https://github.com/bentayloruk/vscode-html-elmish).

From a personal, point of view I know that people love this kind of plugins/feature but there are problems. In general, the plugin will generate the code but it will not necessarily follow your own code convention so you would need to fix it and on really big view it can big hard.

And this plugins is working as long as you don't use project like Fulma to generate your view.

**Comment by alfonsogarciacaro** [comment]
Yes, @bentayloruk's repo is a good way to start :+1: I understand @MangelMaxime's concerns but I think this is still a good a idea, it's been discussed in the past. I just haven't had time to work on it. If you want to give it a go @kfrie we'll help you with that!

The tool doesn't need to be perfect. Probably just copying the tags and the class name will save a lot of work, for example when copying Bulma samples directly from HTML.

Tip: in Fable.React 2.0 beta you can also use `Class` instead of `ClassName` for the class name.

**Comment by kfrie** [comment]
Thank you a lot Maxime. 
Currently I'm evaluating Bulma and a[ template based on Materialize](https://pixinvent.com/materialize-material-design-admin-template/landing/) with a lot of relatively small HTML-crafted components, so it should do the trick for that job. I think for this prototyping kind of stuff it can be super nice.

Of course you are right that thinks will get messy with very large HTML.

**Comment by kfrie** [comment]
@bentayloruk : if there is a newer VSIX than the one I downloaded from your repo that would be great!

@alfonsogarciacaro : I might give it a shot. I never wrote a VS Code plugin though, but the problem does not sound too complicated. I try out the one from @bentayloruk and see how that works and where there might be still some problems. If I get stuck somehow, I would appreciate some help from you guys 😃 

Personally I don't think that the code emitted by the tool needs to be perfect in the first place. I think a lot of people like me who use Fable and the SAFE stack for the first time (like me) are likely to start from some HTML template or CSS framework and it would allow for fast prototyping and a even better on-boarding experience (I can't stress enough how great it already is) Thanks for your help so far!

**Comment by bentayloruk** [comment]
@kfrie hah, I forgot I'd linked that!  I think that was the latest.

**Comment by kfrie** [comment]
I tried out the extension from @bentayloruk and it does a great job already. I used it in conjuction with the [Bulma VS Code snippets](https://marketplace.visualstudio.com/items?itemName=demijollamaxime.bulma). 

The following workflow feels great (assuming the SAFE BookStore sample):

1. expand the snippet you want in `index.html`
2. refine the layout directly within `index.html`
3. use @bentayloruk extension and define view function of Elmish component
4. reset `index.html`
5. wire up logic for component

This enables an almost seamless transition from prototype to production code. I think this approach (and using Bulma - making it the B-SAFE stack 😄) should be communicated for on-boarding since nothing generates a better feeling of accomplishment that the ability to generate great looking pages right from the start.

One thing that could be improved would be a prompt for module prefixes to use before generating F# code, i.e. if somebody wants to use the following style:

```fsharp
module R = Fable.Helpers.React
module P = Fable.Helpers.React.Props
```
Afaik @bentayloruk 's extension is not written with Fable right? Maybe we could do a relaunch of it for with Fable 2.0. I might try to get my head into VS Code plugin development next week ...

**Comment by bentayloruk** [comment]
@kfrie glad you're up and running!

You're right about the extension not being in Fable.  The extension is a hard fork of [this](https://github.com/rubymaniac/vscode-html-to-elm) and was hacked just enough to work for my need at the time.  It could be a lot better, but I'm working with Fulma at the moment and have no plans to do any work on the plugin.

**Comment by MangelMaxime** [comment]
This has been include in Ionide and there is also an online version [here](https://mangelmaxime.github.io/html-to-elmish/)
