### ISSUE TITLE
ICSSProp vs. CSSProp?

### ISSUE THREAD

**Issue by chadunit** [fable-compiler/fable-react#56]
I'm curious what is the use for ICSSProp? I have some hassles using ICSSProp that work better using CSSProp directly.

Consider this initial (working) code:
```
let view1 model =
  div [
    Style [
      BackgroundColor model.BackgroundColor
      BackgroundImage model.BackgroundImage
      BackgroundPosition model.BackgroundPosition
    ]
  ] []
```

Now suppose I want to use yield syntax to have conditional style properties:
```
let view2 model =
  div [
    Style [
      yield BackgroundColor model.BackgroundColor
      if model.HasBackgroundImage then
        yield BackgroundImage model.BackgroundImage
        yield BackgroundPosition model.BackgroundPosition
    ]
  ] []
```

That won't compile:
```
This expression was expected to have type
    'ICSSProp'    
but here has type
    'CSSProp'
```

So I have to cast or unbox everything:
```
let view3 model =
  div [
    Style [
      yield BackgroundColor model.BackgroundColor :> ICSSProp // cast example
      if model.HasBackgroundImage then
        yield !! BackgroundImage model.BackgroundImage // unbox examples
        yield unbox BackgroundPosition model.BackgroundPosition
    ]
  ] []
```

However, if I define my own `Style'` to use CSSProp instead of ICSSProp, then I don't have the extra hassle of casting/unboxing and it still works fine at runtime:
```
let inline Style' (css: CSSProp list): HTMLAttr =
    !!("style", keyValueList CaseRules.LowerFirst css)

let view4 model =
  div [
    Style' [
      yield BackgroundColor model.BackgroundColor
      if model.HasBackgroundImage then
        yield BackgroundImage model.BackgroundImage
        yield BackgroundPosition model.BackgroundPosition
    ]
  ] []
```

Unless there's something important about ICSSProp or some better syntax I can use, maybe the internal `Style` could be defined this way?

**Comment by alfonsogarciacaro** [comment]
There MUST be a reason... I just don't remember what it is, let me check 😅 BTW, you can use `upcast` instead of `unbox`, which is type safe and it'll be also erased in JS code. But I acknowledge it's still annoying.

**Comment by chadunit** [comment]
Ah, thanks for type-safe `upcast` tip, that's a little better since I'm adding the yields anyway and don't have to repeat the type. Plus it also works with e.g. `IHTMLProp list`. 👍 I guess ICSSProp was probably modeled like IHTMLProp but ended up with only one implementer.

**Comment by alfonsogarciacaro** [comment]
Your guess is probably right. I had a look at the source and I don't remember why I exactly did it like that 😅 

![](https://media.giphy.com/media/QcXNIfuQ8Oq4M/giphy.gif)

Maybe it was a simpler way to solve the top-down order in F#, but we can use `module rec` or `and` for that. I'm ok with removing `ICSSProp` 👍

**Comment by chadunit** [comment]
Given that IHTMLProp has the same "problem", I was wondering if there was any thought given to removing the interfaces altogether and combining HTMLAttr+DOMAttr+Prop into one big DU so it could also have a homogeneous list type. Maybe other downsides though.

Anyway I made a computation expression to coerce the yielded types so I'm not even that bothered by this anymore. It's more syntax up front but better than casting every yield IMO. It's a suitable workaround for me so it's fine if we want to close this and not mess with it for now.

```
type CompatibleList<'a>() =
  member x.Yield(item:'a) : 'a list = List.singleton item
  member x.Combine(left:'a list, right:'a list) : 'a list = List.append left right
  member x.Delay(fn:unit -> 'a list) : 'a list = fn()
  member x.Zero() : 'a list = List.empty<'a>
  member x.For(expr:'b seq, fn:'b -> 'a list) : 'a list = expr |> Seq.toList |> List.collect fn

let cssprops = CompatibleList<ICSSProp>()
let htmlprops = CompatibleList<IHTMLProp>()

let view model =
  div <| htmlprops {
    yield Id "view"
    yield Style <| cssprops {
      yield Margin 0
      yield Padding 0
    }
  } <| [
    span [] [ str "hello" ]
  ]
```

**Comment by alfonsogarciacaro** [comment]
IIRC DOMAttr and HTMLAttr had to be separated because SVG elements accept the former but not the latter.
