### ISSUE TITLE
Adding React Table

### ISSUE THREAD

**Issue by realvictorprm** [fable-compiler/fable-react#61]
Hello fellows.
I've tried to get the React-Table extension working with F# and Fable but so far I haven't had much success.

Currently I try to use this code (similar used for React Charts here):
```fsharp
let inline reactTable (props: IProp list) (children: React.ReactElement list): React.ReactElement =
    ofImport "ReactTable" "react-table" (keyValueList CaseRules.LowerFirst props) children
```
to get an ReactTable element. However it already fails here. I've checked many things, e.g dependencies, configurations ... but I won't get rid of the message that the element is unknown to React:
> Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined

After I tried to fix this stuff for some hours I'm asking for help 😢 Maybe I missed something super stupid here?

PS: Future plan is to hand my results over to this repository!

**Comment by alfonsogarciacaro** [comment]
I can see two things here: first, according to the [ReacTable docs](https://react-table.js.org/#/story/readme) you need a **default** import. See https://github.com/fable-compiler/fable-react/issues/60#issuecomment-368276829

Second, `IProp` and friends are only used for **builtin** React elements: basically those representing HTML tags (`div`, `input`, etc). Other components define their own props, so you need to check the documentation and pass the props as a plain JS object. You can [check here]() the different options to define JS objects in Fable.

I haven't tested it, but you should be able to initiate a ReactTable component with code similar to the following (from the ReactTable example):

```fsharp
open Fable.Core
open Fable.Core.JsInterop

// Helpers for dynamic typing
let inline (~%) x = createObj x
let inline (=>) k v = k ==> v

type [<Pojo>] Person =
    { name: string; age: int; friend: Person option }

let data =
    [| { name = "Tanner Linsley"
         age = 26
         friend = Some { name = "Jason Maurer"
                         age = 23
                         friend = None } } |]
let columns =
    [| %["Header" => "Name"
         "accessor" => "name"]
       %["Header" => "Age"
         "accessor" => "age"
         "Cell" => fun props -> span [Class "number"] [str !!props?value]]
       // Define other columns in a similar way
    |]

ofImport "default" "react-table" %["data"=>data; "columns"=>columns] []
```

**Comment by realvictorprm** [comment]
@alfonsogarciacaro you're are a genius. Wow. Thank you so much, I've spend many hours today and you just solved the issue within a couple of minutes, amazing!

In short: Your example works instantly if a single change is applied, replace `Class` with `ClassName`.

PS: Yeah I finally can go on! 😄

**Comment by alfonsogarciacaro** [comment]
I'm no genius, I just happen to be the one who wrote the bindings ;) If anything, it means the API is not intuitive enough and we lack documentation. I'm a bit busy now with Fable 2, if you could write a post about importing external React elements it'd be great!

**Comment by realvictorprm** [comment]
Sounds like a plan :D :) I'll try my best :)

Am 26.02.2018 17:43 schrieb "Alfonso Garcia-Caro" <notifications@github.com
