### ISSUE TITLE
Publish NuGet package with latest changes

### ISSUE THREAD

**Issue by irium** [fable-compiler/fable-react#67]
There are very useful latest changes, but it is not published yet. Especially about added many missing CSS props - manually managing them is annoying.

**Comment by alfonsogarciacaro** [comment]
Ups, sorry. There were some breaking changes so I was waiting to finish some design discussions before releasing a new major version (there's also #65 now). But we can push a prerelease so you can use the latest changes :)

**Comment by irium** [comment]
Yes. Prerelease would be enough :)

**Comment by alfonsogarciacaro** [comment]
Published as 3.0.0-alpha-001 :)

**Comment by irium** [comment]
Thanks a lot!
