### ISSUE TITLE
Unable to resolve module events... when bundling index.android.js

### ISSUE THREAD

**Issue by fkhosrow** [fable-compiler/fable-react#77]
Hi, 
I downloaded and installed the Fable.Recharts NuGet package in my app (I used the SAFE-NIGHTWATCH app as my starting point). I am currently getting the following error when bundling index.android.js:

Bundling `index.android.js`  [development, non-minified, hmr disabled]  0.0% (5/693), failed.
error: bundling failed: "Unable to resolve module `events` from `D:\\Dev\\feature-create-charts\\node_modules\\recharts\\lib\\util\\Events.js.

I checked and the file is there.

Any help to resolve this issue will be appreciated. Thanks!

**Comment by alfonsogarciacaro** [comment]
Hmm, I'm not sure. Looks like there may be a conflict between the `Events` file and node's `events` module. Please note Recharts is a library for the web and I think it's not intended for mobile, though apparently some people managed to do that, please [check this thread](https://github.com/recharts/recharts/issues/188).

**Comment by fkhosrow** [comment]
Thanks @alfonsogarciacaro for the response. In that case, is there a chart library I can use for mobile development that has been ported to Fable? If not, is there a particular library you would recommend in react-native for this purpose? Thanks for your help.

**Comment by alfonsogarciacaro** [comment]
Hmm, not that I'm aware of. Maybe @forki knows of someone? A quick Google search revealed [this library](https://github.com/JesperLekland/react-native-svg-charts). Unfortunately it doesn't have a TypeScript definition, but you can still [interact with JS from Fable](http://fable.io/docs/interacting.html) or write your own bindings like the [Rechart one](https://github.com/fable-compiler/fable-react/blob/4dec6b9e4b4e2895efc1fd1cde2053724ab1e426/src/Fable.Recharts/Fable.Recharts.fs#L601).

**Comment by fkhosrow** [comment]
Thank you @alfonsogarciacaro. I will take a look at that library. Thanks again for your help.
