### ISSUE TITLE
Custom CSS property is accessible in the editor but not when compiling

### ISSUE THREAD

**Issue by inosik** [fable-compiler/fable-react#89]
``` fsharp
let divStyle =
  [
    Width "100px"
    Height "100px"
    Custom ("background", "red")
  ]
div [ Style divStyle ] []
```

This works fine in the editor and when doing `dotnet build`, but Fable emits this error:

``` text
ERROR in ./src/App.fs
G:/projects/demo/src/App.fs(129,12): (129,18) error FSHARP: The value or constructor 'Custom' is not defined. Maybe you want one of the following:
   CustomEqualityAttribute
 @ ./src/CSSDemo.fsproj 1:0-25 1:0-25
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/CSSDemo.fsproj
```

The problem is this:

https://github.com/fable-compiler/fable-react/blob/4f9d7a1dded3c00e730c5586b24ffc99c17a627f/src/Fable.React/Fable.Helpers.React.fs#L160-L165

I guess the DLL in the NuGet package (v3.1.2) was compiled without `FABLE_COMPILER`, so it contains this union case. But when compiling using Fable, it picks up the source file and can't find the union case, because Fable defines `FABLE_COMPILER`. To fix the error, you have to use `CSSProp.Custom`.

~~Also, why does the static method return an `SVGAttr` instead of a `CSSProp`?~~

**Comment by MangelMaxime** [comment]
@inosik This return an `SVGAttr` because this is the `Custom` attribute of `SVGAttr`

Each `Attr` type have is own `Custom` case.

**Comment by inosik** [comment]
Shame on me 😄 

This is the right code:

https://github.com/fable-compiler/fable-react/blob/4f9d7a1dded3c00e730c5586b24ffc99c17a627f/src/Fable.React/Fable.Helpers.React.fs#L729-L734

**Comment by inosik** [comment]
> IMO we should remove the compiler directive and only provide the `static member inline Custom`

We have to keep the union case for SSR, but it shouldn't be accessible. Unfortunately, you can't make a union case private in F#.

We could do something like this:

``` fsharp
// FS0044: This construct is deprecated.
#nowarn "44"
type CSSProp =
    | [<Obsolete("Use the custom-method instead.")>]
      Custom of string * obj

    static member custom (key : string, value : obj) : CSSProp =
#if FABLE_COMPILER
        !!(key, value)
#else
        Custom (key, value)
#endif
#warn "44"
```

Ideally we would make it a compiler error with `[<Obsolete("...", true)>]`, but then we can't use it inside of the `custom`-method.

**Comment by alfonsogarciacaro** [comment]
Using `| [<Erased>] Custom of string * obj` should work and may solve the problem (I added that behavior afterwards). I'll check...

**Comment by alfonsogarciacaro** [comment]
I have pushed 3.1.3, can you please try and reopen if it's still failing? Thanks!

**Comment by inosik** [comment]
> I have pushed 3.1.3

There's no 3.1.3 on NuGet, but I added the `Fable.Helpers.React.fs` file as a Paket GitHub dependency and it works fine 👍
