### ISSUE TITLE
Ref has incorrect signature

### ISSUE THREAD

**Issue by sebbert** [fable-compiler/fable-react#90]
`Ref` currently takes in a function with the signature `Element -> unit`.

This is incorrect, as per the [react documentation](https://reactjs.org/docs/refs-and-the-dom.html#callback-refs):

> React will call the ref callback with the DOM element when the component mounts, __and call it with null when it unmounts__.

Therefore, `Ref` should take i.e. an `Element option -> unit`.

**Comment by alfonsogarciacaro** [comment]
Good point @sebbert! Hmm, this is somewhat tricky, the fact that `None` compiles to `null` is an implementation detail and it could change in a future Fable version so on one hand it's better not to have such signature (although it's true we're using `optional` to represent Typescript optional fields).

In any case, [`Element` is marked as nullable](https://github.com/fable-compiler/fable-import/blob/af96bb2a93ca8a7bf272d4ed25657f952bdb5ab7/Browser/Fable.Import.Browser.fs#L2496) which means you can use a null check with it: `Ref (fun el -> if isNull el then ... else ...)`

**Comment by sebbert** [comment]
Ah, that makes sense. I'm still new to the specifics of how types are
