### ISSUE TITLE
OnReset is missing in DOMAttr.

### ISSUE THREAD

**Issue by OnurGumus** [fable-compiler/fable-react#93]
OnReset is a valid event for forms but it is missing in DomAttr. Please add it.

**Comment by alfonsogarciacaro** [comment]
Thanks for pointing it out @OnurGumus! Would you mind sending a PR to add it?

**Comment by alfonsogarciacaro** [comment]
Also, remember that a temporary solution is to use `HTMLAttr.Custom("onReset", fun ev -> ...)`

**Comment by OnurGumus** [comment]
Here's the pull request:
https://github.com/fable-compiler/fable-react/pull/94
